### ISSUE TITLE
Docker image fails to support Glee

### ISSUE THREAD

**Issue by eelcofolkertsma** [asyncapi/cli#1207]
### Describe the bug.

npm install fails in new glee project for missing python

I use asyncapi/cli image as poor man’s dev container in assumption that the image brings me all dependencies to work with asyncapi/cli features

my docker engine is hosted on raspberry pi 4

I am happy to work on solution, but also very much new to GitHub Actions and Building docker images.

### Expected behavior

I can install and run-dev a new glee project in container based on asyncapi/cli image

### Screenshots

![image](https://github.com/asyncapi/cli/assets/71253997/c001d3d1-b4ba-4b58-8f12-b13acf7e56bb)

### How to Reproduce

Docker compose up below yaml for running container.
My Docker engine runs on Raspberry Pi 4 current versions of OS and engine
Fresh pull of asyncapi/cli image

Here is compose.yaml

```
version: '3'

services:
  studio:
    image: asyncapi/cli
    ports:
      - "8080:3210"
    volumes:
      - ${PWD}/asyncapi.yaml:/app/asyncapi.yaml
      - ${PWD}/output:/app 
    user: root
    networks:
      - default
    command: start studio
    
networks:
  default: {}
```

1. attach to container for command prompt (I used Portainer)
2. “Asyncapi new glee” to create new project
3. “Cd project”
4. “Npm install”

Install fails for lack of Python.
The container is based on Alpine v3.18.3
Node version 16.20.2
Npm version 8.19.4
No python

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!
