### ISSUE TITLE
CLI exits  the process on invalid file input rather than outputing the error message

### ISSUE THREAD

**Issue by chinma-yyy** [asyncapi/cli#616]
#### Describe the bug
When using the `generate` command for `models` , if an invalid specification file is provided then the cli exits with status code 1 but does not stdout any specific message about what error happened. 

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
- Use command `asyncapi generate models typescript asyncapi.yml`

- Screenshots

![image](https://github.com/asyncapi/cli/assets/112387862/7bb1a3ae-2fd3-4ed8-970a-cec1a9c7c632)

- Link to GitHub repository with project that has issues
- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)
File used 

```yml
asyncapi: '2.5.0'
info:
  title: Streetlights API
  version: '1.0.0'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
server:
  mosquitto:
    url: mqtt://test.mosquitto.org
    protocol: mqtt
channels:
  light/measured:
    publish:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      operationId: onLightMeasured
      message:
        name: LightMeasured
        payload:
          type: object
          properties:
            id:
              type: integer
              minimum: 0
              description: Id of the streetlight.
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              type: string
              format: date-time
              description: Date and time when the message was sent.

```
*Here the file is invalid because the server parameter is at wrong location*
#### Expected behavior

- An error message be displayed something like : `Generator Error: Input is not a corrent AsyncAPI document so it cannot be processed.`
- This will result in understanding what the error is about.

## Additional Context
- The issue is in this line 
https://github.com/asyncapi/cli/blob/9c3bde73ba9e62a1b92dbda0d3c217aa94c92626/src/parser.ts#L83-L84
The issue is that instead of only returning the status of the document it is exiting the process. Rather the approach here https://github.com/asyncapi/cli/blob/9c3bde73ba9e62a1b92dbda0d3c217aa94c92626/src/commands/generate/models.ts#L146-L148 is that we handle the status and make an output of the reason.
