### ISSUE TITLE
Typescript generator incorrect array type generation

### ISSUE THREAD

**Issue by bassedOutt** [asyncapi/cli#864]
I have a following schema in my asyncapi file
```
    SomeRequest:
      type: object
      properties:
        someArray:
          uniqueItems: true
          type: array
          description: Some description
          items:
            type: integer
            format: int64
```
 Here's the generated model
 ```
interface SomeRequest {
  someArray: (number | any)[];
}
export default SomeRequest;
```
I expect `someArray` to be `number[]` not of any type. Looking through the documentation, I did not find such configuration/workaround
