### ISSUE TITLE
When installed as debian package "asyncapi generate fromTemplate asyncapi.yaml @asyncapi/html-template" silently returns 1

### ISSUE THREAD

**Issue by TertiumOrganum1** [asyncapi/cli#941]
#### Describe the bug
When installed as debian package "asyncapi generate fromTemplate asyncapi.yaml @asyncapi/html-template" silently returns 1.

#### How to Reproduce
Install debian package. I'm on Mint 21, so it should work the same way on Ubuntu. everything works except generating documentation. no error message, just red dot in vscode console: command returns 1.

#### Expected behavior
should work and generate docs like npm installed version

**Comment by derberg** [comment]
can you please confirm if issue is still there using latest AsyncAPI CLI?

**Comment by bacebu4** [comment]
Got the same problem within gitlab CI

Reproduction .gitlab-ci.yaml

```yaml
pages:
  image: node:lts
  before_script:
    - npm install -g @asyncapi/cli
  script:
    - asyncapi generate fromTemplate https://bit.ly/asyncapi @asyncapi/html-template -o example
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  ```
