### ISSUE TITLE
CLI cannot generate fromTemplate when specification contains file path $refs

### ISSUE THREAD

**Issue by Laupetin** [asyncapi/cli#944]
#### Describe the bug
When trying to generate with the html-template the process will fail when the specification file uses a `$ref` element that points to another file.

It will just show the following message and exit (The error message itself unfortunately is not really helpful):
```
Generator Error: Input is not a correct AsyncAPI document so it cannot be processed.
```

After adding a bit of logging it seems to me that it fails to resolve the path and cannot load the referenced file.

#### How to Reproduce

Running the following command will fail:
```shell
asyncapi generate fromTemplate ./index.yaml @asyncapi/html-template
```

when used with the following specification files:

```yaml
# index.yaml
asyncapi: 2.5.0
info:
  title: Example
  version: 0.1.0
channels:
  user/signedup:
    $ref: subfolder/user-signedup.yaml
```

```yaml
# subfolder/user-signedup.yaml
subscribe:
  message:
    description: An event describing that a user just signed up.
    payload:
      type: object
      additionalProperties: false
      properties:
        fullName:
          type: string
        email:
          type: string
          format: email
        age:
          type: integer
          minimum: 18
```

#### Expected behavior
The cli manages to generate output using the html-template and the given specification.

Running the generator directly instead of the cli does in fact produce the expected result:
```shell
ag index.yaml @asyncapi/html-template
```
